name: mall_ukm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  effective_dart: 1.3.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

