name: mall_ukm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  flutter: 
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.4
  flutter_custom_carousel_slider: ^1.0.6
  persistent_bottom_nav_bar: ^5.0.2
  search_page: ^2.3.0
  cart_stepper: ^4.3.0
  http: ^1.1.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  get_storage: ^2.1.1
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  phosphor_flutter: ^1.4.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  location: ^6.0.2
  cached_network_image: ^3.3.0
  loading_animation_widget: ^1.2.1
  rflutter_alert: ^2.0.7
  awesome_dialog: ^3.2.1
    


dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
  win32: ^5.5.0

flutter: 
  uses-material-design: true
  assets:
  - assets/images/

