name: mall_ukm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.4
  flutter_custom_carousel_slider: ^1.0.0
  persistent_bottom_nav_bar: ^5.0.2
  anim_search_bar: ^2.0.3
  search_page: ^2.3.0
  flutter_svg: ^1.1.6
  cart_stepper: ^4.1.1
  shared_preferences: ^2.2.0
  http: ^0.13.5
  dio: ^5.2.1+1
  shimmer: ^3.0.0
  flutter_survey: ^0.1.4
  fluttertoast: ^8.2.2
  get_storage: ^2.1.1
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  phosphor_flutter: ^2.0.0
  webview_flutter: ^4.0.7
  url_launcher: ^6.1.11


dev_dependencies: 
  flutter_lints: ^2.0.0
  effective_dart: 1.3.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/

